from django.db import models

# Create your models here.
class Announcement(models.Model):
    AnnounceId = models.AutoField(primary_key=True)
    Title = models.TextField()
    Description = models.TextField(blank=True, null=True)
    Date = models.DateField(blank=True, null=True)
    Month = models.CharField(max_length=255, blank=True, null=True)
    Year = models.IntegerField(blank=True, null=True)
    Status = models.CharField(max_length=255, blank=True, null=True)
    createdAt = models.DateTimeField()
    updatedAt = models.DateTimeField()

class Attendance(models.Model):
    AttendanceID = models.AutoField(primary_key=True)
    LoginTime = models.TimeField(blank=True, null=True)
    LogoutTime = models.TimeField(blank=True, null=True)
    locationName = models.CharField(max_length=255, blank=True, null=True)
    locationNameLogout = models.CharField(max_length=255, blank=True, null=True)
    Date = models.DateField()
    Late = models.IntegerField(blank=True, null=True)
    Leave = models.BooleanField(default=False)
    TotalLeave = models.IntegerField(default=0)
    Latitude = models.FloatField(blank=True, null=True)
    Longitude = models.FloatField(blank=True, null=True)
    Daily_Task1 = models.TextField(blank=True, null=True)
    Daily_Task2 = models.TextField(blank=True, null=True)
    Daily_Task3 = models.TextField(blank=True, null=True)
    Daily_Task4 = models.TextField(blank=True, null=True)
    Late_Task = models.TextField(blank=True, null=True)
    createdAt = models.DateTimeField()
    updatedAt = models.DateTimeField()
    EmployeeID = models.IntegerField(blank=True, null=True)

class EmployeeInfo(models.Model):
    EmployeeID = models.AutoField(primary_key=True)
    Name = models.CharField(max_length=255)
    Contact = models.CharField(max_length=255, blank=True, null=True)
    Birth = models.CharField(max_length=255, blank=True, null=True)
    Email = models.CharField(max_length=255)
    JoiningDate = models.DateTimeField(blank=True, null=True)
    BloodGroup = models.CharField(max_length=255, blank=True, null=True)
    EmergencyContact = models.CharField(max_length=255, blank=True, null=True)
    PrimaryContact = models.CharField(max_length=255, blank=True, null=True)
    SecondaryContact = models.CharField(max_length=255, blank=True, null=True)
    NID = models.CharField(max_length=255, blank=True, null=True)
    PDF_NDA = models.CharField(max_length=255, blank=True, null=True)
    ResignationDate = models.DateTimeField(blank=True, null=True)
    LeaveDate = models.DateTimeField(blank=True, null=True)
    AttendanceToggle = models.BooleanField(default=False)
    Qualification = models.CharField(max_length=255, blank=True, null=True)
    Address = models.TextField(blank=True, null=True)
    Telephone = models.CharField(max_length=255, blank=True, null=True)
    Designation = models.CharField(max_length=255, blank=True, null=True)
    Details = models.TextField(blank=True, null=True)
    CasualLeaveLeft = models.IntegerField(default=7)
    SickLeaveLeft = models.IntegerField(default=9)
    Image = models.ImageField(upload_to='employee/', blank=True, null=True)  
    createdAt = models.DateTimeField()
    updatedAt = models.DateTimeField()

class Leave(models.Model):
    Leave_ID = models.AutoField(primary_key=True)
    DateApplied = models.CharField(max_length=255)
    Date = models.CharField(max_length=255)
    Month = models.CharField(max_length=255)
    Total = models.CharField(max_length=255)
    Type = models.CharField(max_length=255)
    Status = models.IntegerField()
    Address = models.TextField(blank=True, null=True)
    Contact = models.CharField(max_length=255, blank=True, null=True)
    Cause = models.TextField(blank=True, null=True)
    Name = models.CharField(max_length=255, blank=True, null=True)
    Designation = models.CharField(max_length=255, blank=True, null=True)
    createdAt = models.DateTimeField()
    updatedAt = models.DateTimeField()
    EmployeeID = models.IntegerField(blank=True, null=True)

class Project(models.Model):
    ProjectID = models.AutoField(primary_key=True)
    From = models.CharField(max_length=255, blank=True, null=True)
    To = models.PositiveIntegerField(blank=True, null=True)
    Name = models.TextField(blank=True, null=True)
    TechnicalExperience = models.TextField(blank=True, null=True)
    ManagerialExperience = models.TextField(blank=True, null=True)
    createdAt = models.DateTimeField()
    updatedAt = models.DateTimeField()
    EmployeeID = models.IntegerField(blank=True, null=True)

class TodoAdmin(models.Model):
    TodoAdminID = models.AutoField(primary_key=True)
    title = models.TextField()
    description = models.TextField(blank=True, null=True)
    timeFrom = models.CharField(max_length=255)
    timeTo = models.CharField(max_length=255)
    Date = models.CharField(max_length=255)
    Month = models.CharField(max_length=255)
    Year = models.IntegerField()
    Status = models.BooleanField()
    createdAt = models.DateTimeField()
    updatedAt = models.DateTimeField()
    adminID = models.IntegerField(blank=True, null=True)

class TodoEmployee(models.Model):
    TodoEmployeeID = models.AutoField(primary_key=True)
    title = models.TextField()
    description = models.TextField(blank=True, null=True)
    timeFrom = models.CharField(max_length=255)
    timeTo = models.CharField(max_length=255)
    Date = models.CharField(max_length=255)
    Month = models.CharField(max_length=255)
    Year = models.IntegerField()
    Status = models.BooleanField()
    createdAt = models.DateTimeField()
    updatedAt = models.DateTimeField()
    EmployeeID = models.IntegerField(blank=True, null=True)